
<h1> 
    &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  
    &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;   
    &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;     
<?php 
echo  $this->current_date_and_time;

echo "WELCOME";?><br></h1>
<html>
<head>
</head>
<body><br><br><br>
    
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    <a href="/user/login">signup-NewUser</a>
    
<?php 
echo  $this->current_date_and_time;

echo "WELCOME";?><br>
<html>
<head>
</head>
<body>
    <a href="#">login-ExistingUser</a><br>
     <a href="/user/login">signup-NewUser</a>

    
    
    
    <?php $this->headTitle('Login'); ?>

<h1>Login</h1>

<?php echo $this->form->setAction($this->url());  ?>

    </body>
    </body>
   <html>
    