<!Doctype html>
<html lang="en">
<head>
    <meta content=""  charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <?php echo $this->headTitle(); ?>
  <?php echo $this->headLink()->appendStylesheet($this->baseUrl().'/css/style.css'); ?>
</head>
<body>
  <div id="content">
<?php echo $this->layout()->content;   ?>
</div>
<h1> <font color:red>START  TWITTER </font></h1>

</body>
</html>