

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
  <form id="logup" class="form-signup" name="<?php echo  $this->escape($this->logup->getName()) ?>" method="<?php echo  $this->escape($this->logup->getMethod() ) ?>" action="<?php echo  $this->escape($this->logup->getAction() ) ?>" >
<?php echo "test";exit; ?>
     <label>UserName</label>
<?php echo $this->logup->username; ?><br>
     <label>Password</label>
<?php echo $this->logup->password; ?><br>


<?php echo $this->logup->Submit; ?><br>

</form>

